
CC=gcc
BIN = imremap

MODULES=utils imremap_source

SOURCES=$(MODULES:%=%.c)
OBJS=$(MODULES:%=%.o)

INCS= -I. -I../include -I/opt/local/include 

LDFLAGS=-L. -L/opt/local/lib -L/usr/lib

LIBS =-lm

CFLAGS = $(INCS) -Wall -Wstrict-prototypes -O3 

all: $(BIN)

imremap: imremap.c $(OBJS)
	$(CC) $(CFLAGS) -o ./imremap $^ $(LDFLAGS) $(LIBS)

clean:
	$(RM) *.o

purge: clean
	$(RM) -rf ./imremap

.PHONY: all clean



-include .make_imremap


